#!/usr/bin/env bash
#
# Summary: Executes a CLI command
#
# Usage: docli exec CLI_NAME [CLI_ARGS]
#
# Executes a registered CLI command using its Docker image and
# entrypoint.
#
# This commands mounts your $HOME into Docker's container home
# and make you current dir as PWD inside the container. This
# simulates the CLI execution inside the container.

set -e

function pwdhome {
  echo ${PWD/$HOME\//}
}

service="$1"
image=$(python src/docli_config.py get_service_image $service)
entrypoint=$(python src/docli_config.py get_service_entrypoint $service)
cli_args_arr=($@)
cli_args="${cli_args_arr[@]:1}"

python src/docli_config.py exists $service || (
  echo "CLI '$service' not registered" && exit 1
)

cmd="docker run -ti --rm -v $HOME:/root -w /root/$(pwdhome)"
[ -n "$entrypoint" ] && cmd="$cmd --entrypoint $entrypoint"
cmd="$cmd $image $cli_args"

$cmd
