#!/usr/bin/env bash
#
# Summary: Rehash docli shims (run this if some shim is missing)
#
# Usage: docli rehash

mkdir -p $DOCLI_ROOT/shims

services=$(python $DOCLI_ROOT/src/docli_config.py list_services)

for service in $services; do
  rm -f $DOCLI_ROOT/shims/$service
  ln -s $DOCLI_ROOT/libexec/docli $DOCLI_ROOT/shims/$service
done
